import assert from "node:assert/strict";
import { test } from "node:test";
import { buildIndex, parseTask, shortStatus } from "./backlog-index.mjs";

const task = (id, title, type, status) =>
  `<a id="${id.toLowerCase()}"></a>\n# ${id} · ${title}\n- **Type:** ${type} · **Status:** ${status} · **Depends on:** —\n- **What:** x\n`;

const tasks = new Map(
  [
    ["FLOW-901", "Widget reads", "BUG", "done (#12, server; app #14)"],
    ["FLOW-902", "Gadget sheet", "SMALL UI", "in-progress (UI lane 2, 2026-10-09, branch x)"],
    ["FLOW-903", "Parked idea", "PLAN FIRST", "future (owner, 2026-10-09)"],
  ].map(([id, title, type, status]) => [id, parseTask(id, task(id, title, type, status))]),
);

const source = `# Flow backlog

Intro.

## Priority queue

| # | Id |
| --- | --- |
| 1 | FLOW-902 |
| 1b | FLOW-901 |

## Area

Area intro.

- FLOW-901
- FLOW-902

## Future features

| Id | Parked |
| --- | --- |
| FLOW-903 | 2026-10-09 |
`;

test("parseTask reads the title, type, status and lane", () => {
  assert.deepEqual(tasks.get("FLOW-902"), {
    id: "FLOW-902",
    title: "Gadget sheet",
    type: "SMALL UI",
    status: "in-progress (UI lane 2, 2026-10-09, branch x)",
    lane: "UI lane 2",
  });
  assert.throws(() => parseTask("FLOW-1", "# FLOW-2 · x\n"), /first heading/);
});

test("shortStatus keeps the word and a done task's PR", () => {
  assert.equal(shortStatus("done (#12, server; app #14)"), "done (#12)");
  assert.equal(shortStatus("in-progress (UI lane 2)"), "in-progress");
  assert.equal(shortStatus("ready"), "ready");
});

test("buildIndex expands the queue, the areas and the parked table, with one anchor per task", () => {
  const index = buildIndex(source, tasks);
  assert.match(index, /^# Flow backlog\n\n<!-- Generated by scripts\/backlog-index\.mjs/);
  assert.match(index, /\| 1 \| \[FLOW-902\]\(#flow-902\) \| Gadget sheet \| SMALL UI \| in-progress \|/);
  assert.match(index, /\| 1b \| \[FLOW-901\]\(#flow-901\) \| Widget reads \| BUG \| done \(#12\) \|/);
  assert.match(index, /Area intro\.\n\n\| Id \| Title \| Type \| Status \| Lane \|\n\| --- \| --- \| --- \| --- \| --- \|\n\| <a id="flow-901"><\/a>\[FLOW-901\]\(tasks\/FLOW-901\.md\) \| Widget reads \| BUG \| done \(#12\) \| — \|\n\| <a id="flow-902"><\/a>/);
  assert.match(index, /\| <a id="flow-903"><\/a>\[FLOW-903\]\(tasks\/FLOW-903\.md\) \| Parked idea \| 2026-10-09 \|\n$/);
  assert.equal(index.match(/<a id="flow-902">/g)?.length, 1);
});

test("buildIndex refuses a task listed twice, a missing file, and an unlisted task", () => {
  assert.throws(() => buildIndex(source.replace("- FLOW-902", "- FLOW-902\n- FLOW-901"), tasks), /listed twice/);
  assert.throws(() => buildIndex(source.replace("| 1 | FLOW-902 |", "| 1 | FLOW-999 |"), tasks), /FLOW-999/);
  assert.throws(() => buildIndex(source.replace("- FLOW-902\n", ""), tasks), /does not list FLOW-902/);
});
