#!/usr/bin/env node
// Builds docs/backlog/TASKS.md, the backlog index, from docs/backlog/tasks/index-source.md (the
// header, "Lanes now", the priority order and the areas, owned by the lane manager) and one file per
// task, docs/backlog/tasks/FLOW-<id>.md. A lane edits only its own task file, then runs this script.
//   node scripts/backlog-index.mjs          writes TASKS.md
//   node scripts/backlog-index.mjs --check  fails when TASKS.md is out of date (local CI and CI)
// In the source, three shapes expand from the task files:
//   - a table headed `| # | Id |`: the priority queue, filled with title, type and status;
//   - a table headed `| Id | Parked |`: the future features, filled with the title;
//   - a run of `- FLOW-<id>` lines: an area's table of tasks with title, type, status and lane.
// Every task file is listed exactly once in an area or in the parked table; that row carries the
// task's anchor, so links to TASKS.md#flow-<id> keep working.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const DIR = "docs/backlog";
const TASKS_DIR = `${DIR}/tasks`;
const SOURCE = `${TASKS_DIR}/index-source.md`;
const OUT = `${DIR}/TASKS.md`;
const NOTICE =
  "<!-- Generated by scripts/backlog-index.mjs from tasks/index-source.md and tasks/FLOW-*.md. Edit those, then run `node scripts/backlog-index.mjs`. -->";

const LANES =
  /\b(dev lane \d+|UI lane \d+|backlog bug fixes|bug lane|design lead|lane manager|data agent|file split|production QA)\b/i;

/** Reads one task file: id, title, type, status, lane. */
export function parseTask(id, text) {
  const heading = /^# (FLOW-\d+) · (.+)$/m.exec(text);
  if (!heading || heading[1] !== id) throw new Error(`${id}.md: the first heading must be "# ${id} · <title>"`);
  const fields = /^- \*\*Type:\*\* (.+?) · \*\*Status:\*\* (.+?)(?: · \*\*[^*]+:\*\*.*)?$/m.exec(text);
  if (!fields) throw new Error(`${id}.md: needs a "- **Type:** … · **Status:** …" line`);
  const status = fields[2].trim();
  const lane = LANES.exec(status)?.[1] ?? "—";
  return { id, title: heading[2].trim(), type: fields[1].trim(), status, lane };
}

/** The status for a table: the text before its first note, and the PR of a done task. */
export function shortStatus(status) {
  let short = status.split(/ \(|; |: /)[0].trim();
  if (/^done\b/.test(short) && !/#\d+/.test(short)) {
    const pr = /#\d+/.exec(status);
    if (pr) short = `${short} (${pr[0]})`;
  }
  return short.replace(/\|/g, "\\|");
}

const cell = (text) => text.replace(/\|/g, "\\|");
const anchor = (id) => `<a id="${id.toLowerCase()}"></a>`;
const fileLink = (id) => `[${id}](tasks/${id}.md)`;

/** The index text for the source and the parsed tasks (a Map of id to task). */
export function buildIndex(source, tasks) {
  const lines = source.replace(/\n$/, "").split("\n");
  const out = [];
  const placed = new Map();
  const need = (id, where) => {
    const task = tasks.get(id);
    if (!task) throw new Error(`index-source.md lists ${id} (${where}), but tasks/${id}.md does not exist`);
    return task;
  };
  const place = (id, where) => {
    if (placed.has(id)) throw new Error(`${id} is listed twice in index-source.md (${placed.get(id)} and ${where})`);
    placed.set(id, where);
    return need(id, where);
  };
  let area = "the header";
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (line.startsWith("## ")) area = line.slice(3);
    if (i === 0) {
      out.push(line, "", NOTICE);
      continue;
    }
    if (/^\| # \| Id \|$/.test(line)) {
      out.push("| # | Id | Title | Type | Status |", "| --- | --- | --- | --- | --- |");
      const queued = new Set();
      i += 1;
      while (i + 1 < lines.length && lines[i + 1].startsWith("|")) {
        i += 1;
        const row = /^\| ([^| ]+) \| (FLOW-\d+) \|$/.exec(lines[i]);
        if (!row) throw new Error(`index-source.md: a priority row must read "| <n> | FLOW-<id> |": ${lines[i]}`);
        if (queued.has(row[2])) throw new Error(`${row[2]} is in the priority queue twice in index-source.md`);
        queued.add(row[2]);
        const task = need(row[2], "the priority queue");
        out.push(`| ${row[1]} | [${task.id}](#${task.id.toLowerCase()}) | ${cell(task.title)} | ${cell(task.type)} | ${shortStatus(task.status)} |`);
      }
      continue;
    }
    if (/^\| Id \| Parked \|$/.test(line)) {
      out.push("| Id | Title | Parked |", "| --- | --- | --- |");
      i += 1;
      while (i + 1 < lines.length && lines[i + 1].startsWith("|")) {
        i += 1;
        const row = /^\| (FLOW-\d+) \| ([^|]+) \|$/.exec(lines[i]);
        if (!row) throw new Error(`index-source.md: a parked row must read "| FLOW-<id> | <date> |": ${lines[i]}`);
        const task = place(row[1], area);
        out.push(`| ${anchor(task.id)}${fileLink(task.id)} | ${cell(task.title)} | ${row[2].trim()} |`);
      }
      continue;
    }
    if (/^- FLOW-\d+$/.test(line)) {
      out.push("| Id | Title | Type | Status | Lane |", "| --- | --- | --- | --- | --- |");
      for (; i < lines.length && /^- FLOW-\d+$/.test(lines[i]); i += 1) {
        const task = place(lines[i].slice(2), area);
        out.push(`| ${anchor(task.id)}${fileLink(task.id)} | ${cell(task.title)} | ${cell(task.type)} | ${shortStatus(task.status)} | ${task.lane} |`);
      }
      i -= 1;
      continue;
    }
    out.push(line);
  }
  const missing = [...tasks.keys()].filter((id) => !placed.has(id)).sort();
  if (missing.length > 0) throw new Error(`index-source.md does not list ${missing.join(", ")}: add each under its area`);
  return `${out.join("\n")}\n`;
}

/** Reads the task files under a folder. */
export function readTasks(dir) {
  const tasks = new Map();
  for (const file of readdirSync(dir).sort()) {
    const match = /^(FLOW-\d+)\.md$/.exec(file);
    if (match) tasks.set(match[1], parseTask(match[1], readFileSync(join(dir, file), "utf8")));
    else if (file !== "index-source.md") throw new Error(`tasks/${file}: a task file must be named FLOW-<id>.md (index-source.md is the only other file there)`);
  }
  return tasks;
}

/** Writes TASKS.md under a repo root, or with check, only compares it. Returns the exit code and the message. */
export function run(root, check) {
  const index = buildIndex(readFileSync(join(root, SOURCE), "utf8"), readTasks(join(root, TASKS_DIR)));
  const out = join(root, OUT);
  if (check) {
    const current = existsSync(out) ? readFileSync(out, "utf8") : "";
    if (current !== index) {
      return { code: 1, message: `${OUT} is out of date. Run \`node scripts/backlog-index.mjs\` and commit it (edit tasks/*.md, not TASKS.md).` };
    }
    return { code: 0, message: `${OUT} is up to date.` };
  }
  writeFileSync(out, index);
  return { code: 0, message: `Wrote ${OUT}.` };
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  try {
    // The repo root from this file, so the script works from any folder.
    const { code, message } = run(fileURLToPath(new URL("..", import.meta.url)), process.argv.includes("--check"));
    (code === 0 ? console.log : console.error)(message);
    process.exitCode = code;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
